// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ScoreCpp
List ScoreCpp(const Eigen::SparseMatrix<double>& nrisk, const Eigen::MatrixXd& X, const Eigen::VectorXd& beta, const Eigen::VectorXd& ri, const Eigen::VectorXi& Mi, const Eigen::VectorXi& delta);
RcppExport SEXP _SpaCP_ScoreCpp(SEXP nriskSEXP, SEXP XSEXP, SEXP betaSEXP, SEXP riSEXP, SEXP MiSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type nrisk(nriskSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type ri(riSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi& >::type Mi(MiSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi& >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(ScoreCpp(nrisk, X, beta, ri, Mi, delta));
    return rcpp_result_gen;
END_RCPP
}
// FindrCpp
Eigen::VectorXd FindrCpp(const Eigen::SparseMatrix<double>& nrisk, const Eigen::MatrixXd& X, const Eigen::VectorXd& beta, const Eigen::VectorXd& ri, const Eigen::VectorXi& Mi, const Eigen::VectorXi& delta, const double eta, const double sigma2, const Eigen::MatrixXd& d2, const double lambda);
RcppExport SEXP _SpaCP_FindrCpp(SEXP nriskSEXP, SEXP XSEXP, SEXP betaSEXP, SEXP riSEXP, SEXP MiSEXP, SEXP deltaSEXP, SEXP etaSEXP, SEXP sigma2SEXP, SEXP d2SEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type nrisk(nriskSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type ri(riSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi& >::type Mi(MiSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type d2(d2SEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(FindrCpp(nrisk, X, beta, ri, Mi, delta, eta, sigma2, d2, lambda));
    return rcpp_result_gen;
END_RCPP
}
// MyjacCpp
Eigen::MatrixXd MyjacCpp(const Eigen::SparseMatrix<double>& nrisk, const Eigen::MatrixXd& X, const Eigen::VectorXd& beta, const Eigen::VectorXd& ri, const Eigen::VectorXi& Mi, const Eigen::VectorXi& delta, const double eta, const double sigma2, const Eigen::MatrixXd& d2, const double lambda);
RcppExport SEXP _SpaCP_MyjacCpp(SEXP nriskSEXP, SEXP XSEXP, SEXP betaSEXP, SEXP riSEXP, SEXP MiSEXP, SEXP deltaSEXP, SEXP etaSEXP, SEXP sigma2SEXP, SEXP d2SEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type nrisk(nriskSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type ri(riSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi& >::type Mi(MiSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type d2(d2SEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(MyjacCpp(nrisk, X, beta, ri, Mi, delta, eta, sigma2, d2, lambda));
    return rcpp_result_gen;
END_RCPP
}
// l21Cpp
double l21Cpp(const Eigen::VectorXd& parms, const Eigen::VectorXd& rhat, const Eigen::SparseMatrix<double>& nriskSp, const Eigen::MatrixXd& X, const Eigen::VectorXi& Mi, const Eigen::VectorXi& delta, const Eigen::MatrixXd& d2, const double lambda, const double fail_value);
RcppExport SEXP _SpaCP_l21Cpp(SEXP parmsSEXP, SEXP rhatSEXP, SEXP nriskSpSEXP, SEXP XSEXP, SEXP MiSEXP, SEXP deltaSEXP, SEXP d2SEXP, SEXP lambdaSEXP, SEXP fail_valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type parms(parmsSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type rhat(rhatSEXP);
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type nriskSp(nriskSpSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi& >::type Mi(MiSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type d2(d2SEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const double >::type fail_value(fail_valueSEXP);
    rcpp_result_gen = Rcpp::wrap(l21Cpp(parms, rhat, nriskSp, X, Mi, delta, d2, lambda, fail_value));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SpaCP_ScoreCpp", (DL_FUNC) &_SpaCP_ScoreCpp, 6},
    {"_SpaCP_FindrCpp", (DL_FUNC) &_SpaCP_FindrCpp, 10},
    {"_SpaCP_MyjacCpp", (DL_FUNC) &_SpaCP_MyjacCpp, 10},
    {"_SpaCP_l21Cpp", (DL_FUNC) &_SpaCP_l21Cpp, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_SpaCP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
