# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ScoreCpp <- function(nrisk, X, beta, ri, Mi, delta) {
    .Call(`_SpaCP_ScoreCpp`, nrisk, X, beta, ri, Mi, delta)
}

FindrCpp <- function(nrisk, X, beta, ri, Mi, delta, eta, sigma2, d2, lambda = 1e-5) {
    .Call(`_SpaCP_FindrCpp`, nrisk, X, beta, ri, Mi, delta, eta, sigma2, d2, lambda)
}

MyjacCpp <- function(nrisk, X, beta, ri, Mi, delta, eta, sigma2, d2, lambda = 1e-5) {
    .Call(`_SpaCP_MyjacCpp`, nrisk, X, beta, ri, Mi, delta, eta, sigma2, d2, lambda)
}

l21Cpp <- function(parms, rhat, nriskSp, X, Mi, delta, d2, lambda = 1e-7, fail_value = 1e6) {
    .Call(`_SpaCP_l21Cpp`, parms, rhat, nriskSp, X, Mi, delta, d2, lambda, fail_value)
}

